routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/home', function () {
    return redirect('/admin/beranda');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin-anggota-ajax', 'Web\Admin\AnggotaController@dataAjax');
Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::get('admin/angsuran/index/{id}', 'Web\Admin\AngsuranController@index', ['as' => 'admin']);

Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('export', 'Web\Admin\DownloadController@export_anggota')->name('export');
//cteak formulir
Route::get('admin/akad/cetak/formulir', 'Web\Admin\AkadController@formulir')->name('admin.akad.cetak.formulir');

app/Akad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Akad extends Model
{
    protected $guarded = [];
    protected $dates = ['tanggal', 'created_at'];

    public function anggota()
    {
        return $this->belongsTo('App\Anggota', 'anggota_id');
    }
    public function angsuran()
    {
        return $this->hasMany('App\Angsuran');
    }
}

app/Http/Controllers/Web/Admin/AkadController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Akad;
use App\Anggota;
use App\Angsuran;
use App\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AkadController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $data = Akad::orderBy('id', 'DESC')->get()->all();
        return view('admin.akad.beranda', compact('data', 'no'));
    }

    public function dataAjax(Request $request)
    {
        $data = [];
        if ($request->has('q')) {
            $search = $request->q;
            $data = DB::table("anggotas")
                ->select("id", "nama")
                ->where('nama', 'LIKE', "%$search%")
                ->get();
        }


        return response()->json($data);
    }

    public function create()
    {
        $anggota = Anggota::orderBy('nama', 'ASC')->get()->all();
        return view('admin.akad.create', compact('anggota'));
    }

    public function formulir()
    {
        return view('admin.akad.formulir');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        Akad::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Akad.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Akad berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.akad.index')->with($notification);
    }

    public function show($id)
    {
        $no = 1;
        $data = Akad::findOrFail($id);
        $barang = Angsuran::where('akad_id', $id)->get()->all();
        return view('admin.akad.show', compact('data', 'barang', 'no'));
    }

    public function edit($id)
    {
        $anggota = Anggota::orderBy('nama', 'ASC')->get()->all();
        $data = Akad::findOrFail($id);
        return view('admin.akad.edit', compact('data', 'anggota'));
    }

    public function update(Request $request, $id)
    {
        $data = Akad::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Akad.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Akad berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.akad.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Akad::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Akad.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Akad berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.akad.index')->with($notification);
    }
}

resources/views/admin/akad/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Akad
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2">
                <a href="{{ route('admin.akad.create') }}" class="btn btn-primary">+ Akad</a>
            </div>
            <div class="col-md-2">
                <a href="{{ route('admin.akad.cetak.formulir') }}" class="btn btn-success" target="_blank">Cetak Formulir</a>
                <br><br>
            </div>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Akad</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Akad ID</th>
                                <th>Nama</th>
                                <th>Nomor</th>
                                <th>Tanggal</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->id }}</td>
                                <td>{{ $item->anggota->nama }}</td>
                                <td>{{ $item->nomor }}</td>
                                <td>{{ tanggal_local($item->tanggal)}}</td>
                                <td align="center">
                                    <form action="{{ route('admin.akad.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-primary" href="{{ route('admin.akad.show',$item->id) }}" target="_blank">Cetak</a>
                                        <a class="btn btn-success" href="{{ route('admin.akad.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/akad/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Akad
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data Akad</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.akad.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-12">
                            <hr>
                            Anggota
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nama</label>
                                <div class="col-sm-8">
                                    <select class="select2 form-control" name="anggota_id">
                                        <option value="-">-</option>
                                        @foreach($anggota as $ang)
                                        <option value="{{$ang->id}}">{{$ang->nama}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nomor</label>

                                <div class="col-sm-8">
                                    <input type="text" name="nomor" class="form-control" placeholder="Nomor" >
                                    <small class="text-danger">{{ $errors->first('nomor') }}</small>
                                </div>
                            </div>
                            <hr>
                            Pasal 5
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jangka Waktu</label>

                                <div class="col-sm-8">
                                    <input type="number" name="pasal5_a" class="form-control" placeholder="Jangka Waktu / Bulan">
                                    <small class="text-danger">{{ $errors->first('pasal5_a') }}</small>
                                </div>
                            </div>
                            <hr>
                            Tanggal
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanggal</label>

                                <div class="col-sm-8">
                                    <input type="date" name="tanggal" class="form-control">
                                    <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/akad')}}" class="btn btn-default  pull-right">Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.select2').select2({
        ajax: {
            url: '{{asset('admin-akad-ajax')}}',
            dataType: 'json',
            delay: 250,
            processResults: function(data) {
                return {
                    results: $.map(data, function(item) {
                        return {
                            text: item.nama,
                            id: item.id
                        }
                    })
                };
            },
            cache: true
        }
    });
</script>
@endsection

resources/views/admin/akad/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Akad
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Akad</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.akad.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-6">
                            <hr>
                            Anggota
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nama</label>
                                <div class="col-sm-8">
                                    <select class="select2 form-control" name="anggota_id">
                                        <option value="{{$data->anggota_id}}">{{$data->anggota->nama}}</option>
                                        @foreach($anggota as $ang)
                                        <option value="{{$ang->id}}">{{$ang->nama}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('anggota_id') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nomor</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->nomor}}" name="nomor" class="form-control">
                                    <small class="text-danger">{{ $errors->first('nomor') }}</small>
                                </div>
                            </div>
                            <hr>
                            Pasal 5
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jangka Waktu</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->pasal5_a}}" name="pasal5_a" class="form-control" placeholder="Jangka Waktu / Bulan">
                                    <small class="text-danger">{{ $errors->first('pasal5_a') }}</small>
                                </div>
                            </div>
                            <hr>
                            Tanggal
                            <hr>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanggal</label>

                                <div class="col-sm-8">
                                    @if(empty($data->tanggal))
                                    <input type="date" name="tanggal" class="form-control">
                                    @else
                                    <input type="date" value="{{ $data->tanggal->format('Y-m-d') }}" name="tanggal" class="form-control">
                                    @endif
                                    <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                                </div>
                            </div>
                            <a href="{{url('admin/akad')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.select2').select2({
        ajax: {
            url: '{{asset('admin-akad-ajax')}}',
            dataType: 'json',
            delay: 250,
            processResults: function(data) {
                return {
                    results: $.map(data, function(item) {
                        return {
                            text: item.nama,
                            id: item.id
                        }
                    })
                };
            },
            cache: true
        }
    });
</script>
@endsection

resources/views/admin/akad/footer.blade.php
<table class="table-a" width="100%" style="margin-top: 20px;">
    <tbody>
        <tr class="tr">
            <td class="td" align="center" width="20%">Dipersiapkan oleh</td>
            <td class="td" rowspan="2" align="center"><b>SOP KOPERASI MITRA GRIYA INDONESIA</b></td>
            <td class="td" align="center" width="15%">FINAL</td>
        </tr>
        <tr class="tr" height="30px">
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

resources/views/admin/akad/formulir.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Formulir</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <!-- <link href="{{ asset('itlabil/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet"> -->

    <style>
        @media print {
            @page {
                size: auto !important
            }
        }

        #formulir {
            background-color: #000000;
            color: #ffffff;
        }

        .samping {
            padding: 15px 15px;
        }

        body {
            font-family: 'Source Sans Pro', sans-serif;
            margin: 15px 15px;
        }

        .kanankiri {
            text-align: justify;
        }

        .tengah {
            text-align: center;
        }

        .table-a {
            border-collapse: collapse;
        }

        .table-a,
        .tr,
        .td {
            border: 1px solid black;
            padding-left: 5px;
            padding-right: 5px;
        }
    </style>
</head>

<body onload="window.print()">
    <div class="container">
        <table width="100%">
            <tbody>
                <tr id="formulir">
                    <td class="tengah"><b>FORMULIR PENDAFTARAN</b></td>
                </tr>
                <tr>
                    <td class="tengah"><b>KAMPUNG TAHFIDZ GADINGREJO</b></td>
                </tr>
                <tr>
                    <td>Bismillahirohmanirrohim</td>
                </tr>
                <tr>
                    <td>saya bertanda tangan dibwah ini :</td>
                </tr>
            </tbody>
        </table>
        <table width="100%" class="table-a" style="background-color: #dedede;">
            <tr class="tr">
                <td class="td" width="35%">NOMOR</td>
                <td class="td tengah" width="5%">:</td>
                <td class="td" colspan="5"></td>
            </tr>
            <tr class="tr">
                <td class="td">NAMA</td>
                <td class="td tengah">:</td>
                <td class="tdh" colspan="5"></td>
            </tr>
            <tr class="tr">
                <td class="td">NIK</td>
                <td class="td tengah">:</td>
                <td class="td" colspan="5"></td>
            </tr>
            <tr class="tr">
                <td class="td">TEMPAT /TGL LAHIR</td>
                <td class="td tengah">:</td>
                <td class="td" colspan="5"></td>
            </tr>
            <tr class="tr">
                <td class="td"></td>
                <td class="td tengah">:</td>
                <td class="td" width="10%" style="background-color: #ffffff;"></td>
                <td class="td" colspan="2">Perempuan</td>
                <td class="td" width="10%" style="background-color: #ffffff;"></td>
                <td class="td">Laki - Laki</td>
            </tr>
            <tr class="tr">
                <td class="td">ALAMAT</td>
                <td class="td tengah">:</td>
                <td class="td" style='border:none;'>Desa</td>
                <td class="td" colspan="4" style='border:none;'>:</td>
            </tr>
            <tr class="tr">
                <td class="td"></td>
                <td class="td tengah"></td>
                <td class="td" style='border:none;'>Kec.</td>
                <td class="td" colspan="3" style='border:none;'>:</td>
                <td class="td" style='border:none;'>Kode Pos :</td>
            </tr>
            <tr class="tr">
                <td class="td"></td>
                <td class="td tengah"></td>
                <td class="td" style='border:none;'>Kab.</td>
                <td class="td" colspan="4" style='border:none;'>:</td>
            </tr>
            <tr class="tr">
                <td class="td">JENIS IDENTITAS</td>
                <td class="td tengah">:</td>
                <td class="td" colspan="5">KTP</td>
            </tr>
            <tr class="tr">
                <td class="td">NO WA</td>
                <td class="td tengah">:</td>
                <td class="td" colspan="3" style='border:none;'>Istri:</td>
                <td class="td" colspan="2" style='border:none;'>Suami:</td>
            </tr>
            <tr class="tr">
                <td class="td">1/3 Kaveling ditanam pohon jambu</td>
                <td class="td tengah">:</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" colspan="2">Setuju</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td">Tidak Setuju</td>
            </tr>
            <tr class="tr">
                <td class="td">Kepemilikan diteruskan menjadi SHM db biaya mandiri</td>
                <td class="td tengah">:</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" colspan="2">Setuju</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td">Tidak Setuju</td>
            </tr>
            <tr class="tr">
                <td class="td">REKOMENDASI/INFO DARI</td>
                <td class="td tengah">:</td>
                <td class="td" colspan="5"></td>
            </tr>
            <tr class="tr">
                <td class="td" rowspan="3">PILIHAN PEMBAYARAN</td>
                <td class="td tengah" rowspan="3">:</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" width="10%" colspan="4">CASH</td>
            </tr>
            <tr class="tr">
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" style='border:none;'>DP</td>
                <td class="td" colspan="3" style='border:none;'>Rp :</td>
            </tr>
            <tr class="tr">
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" style='border:none;'>KREDIT</td>
                <td class="td" colspan="" style='border:none;'>Rp :</td>
                <td class="td" style='border:none;'></td>
                <td class="td" align="right" style='border:none;'>per-bulan</td>
            </tr>
            <tr class="tr">
                <td class="td">BLOK KAVELING</td>
                <td class="td tengah">:</td>
                <td class="td" style="background-color: #ffffff;"></td>
                <td class="td" colspan="4"></td>
            </tr>
        </table>
        <table width="100%">
            <tbody>
                <tr>
                    <td colspan="4">Ketentuan :</td>
                </tr>
                <tr>
                    <td width="7%"></td>
                    <td width="3%" valign="top">1.</td>
                    <td colspan="2"><i>Ukuran bidang kaveling adalah 10 m x 15m atau 150M2</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">2.</td>
                    <td colspan="2"><i>Kelebihan ukuran tanah dihitung 300rb/M2</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">3.</td>
                    <td colspan="2"><i>Legalitas surat tanah adalah Surat jual beli dan Sporadik dari Pekon akan diberikan ke Pembeli setelah pelunasan Cicilan</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">4.</td>
                    <td colspan="2"><i>Pembelian dengan cara kredit maksimal lunas adalah 3 tahun</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">5.</td>
                    <td colspan="2"><i>Apabila 3 x berturut-turut konsumen tidak melakukan cicilan, maka Pihak Pengembang bermusyawarah dengan Pembeli untuk dicarikan jalan keluar</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">6.</td>
                    <td colspan="2"><i>Pembeli boleh membangun rumah diatas kaveling selama proses cicilan</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">7.</td>
                    <td colspan="2"><i>Pembeli tidak dibenarkan menstranfer/melakukan cicilan Selain rekening yayasan Ats tsaqib/ Petugas resmi bagian keuangan</i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">8.</td>
                    <td width="23%"><i>Rekening Resmi A.N :</i></td>
                    <td><i>Yayasan Ats-Tsaqib </i></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><i>Bank Syariah Mandiri (451) </i></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><i>Nomor rekening : 7127781658 </i></td>
                </tr>
                <tr>
                    <td></td>
                    <td valign="top">9.</td>
                    <td colspan="2"><i>Pembeli berhak mendapatkan diskon jika melunasi lebih cepat dari waktu akad pertama</i></td>
                </tr>
            </tbody>
        </table>
        <table width="100%">
            <tbody>
                <tr>
                    <td align="right">Gadingrejo,</td>
                    <td width="20%"></td>
                    <td width="10%">
                        2020
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="100%" class="table-a" style="background-color: #dedede;margin-top:10px">
            <tbody>
                <tr class="tr">
                    <td class="td" align="center">
                        Penjual<br><br><br><br><br>
                        ( WAHYUDI )
                    </td>
                    <td class="td" align="center">
                        Pembeli<br><br><br><br><br>
                        (......................)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</body>

</html>

resources/views/admin/akad/halbar.blade.php
<div style='page-break-after:always'></div>

resources/views/admin/akad/header.blade.php
<table class="table-a" width="100%" style="margin-bottom: 15px;">
    <tbody>
        <tr class="tr">
            <td class="td" width="20%" rowspan="5" align="center"><img src="{{asset('itlabil/images/default/kop.png')}}" alt="" width="150px"></td>
            <td class="td" rowspan="3" align="center"><b>AKAD / PERJANJIAN</b></td>
            <td class="td">
                <font size="2px">Indeks</font>
            </td>
            <td class="td"></td>
        </tr>
        <tr class="tr">
            <td class="td">
                <font size="2px">SK Dir</font>
            </td>
            <td class="td"></td>
        </tr>
        <tr class="tr">
            <td class="td">
                <font size="2px">Tgl.Berlaku</font>
            </td>
            <td class="td"></td>
        </tr>
        <tr class="tr">
            <td class="td" rowspan="2" align="center"><b>PENGELOLAAN & PEMBIAYAAN</b></td>
            <td class="td">
                <font size="2px">Tgl.Revisi</font>
            </td>
            <td class="td"></td>
        </tr>
        <tr class="tr">
            <td class="td">
                <font size="2px">Halaman</font>
            </td>
            <td class="td">
                <font size="2px">{{$no}}/11</font>
            </td>
        </tr>
    </tbody>
</table>