routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/home', function () {
    return redirect('/admin/beranda');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin-anggota-ajax', 'Web\Admin\AnggotaController@dataAjax');
Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::get('admin/angsuran/index/{id}', 'Web\Admin\AngsuranController@index', ['as' => 'admin']);

Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('export', 'Web\Admin\DownloadController@export_anggota')->name('export');
//cteak formulir
Route::get('admin/akad/cetak/formulir', 'Web\Admin\AkadController@formulir')->name('admin.akad.cetak.formulir');

app/Anggota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    protected $guarded = [];

    protected $dates = ['tanggal_lahir'];
    public function pekerjaan()
    {
        return $this->belongsTo('App\Pekerjaan', 'pekerjaan_id');
    }

    public function akad()
    {
        return $this->hasMany('App\Akad');
    }
}

app/Http/Controllers/Web/Admin/AnggotaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Anggota;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\AnggotaRequest;
use App\Pekerjaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AnggotaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $data = Anggota::orderBy('nama', 'ASC')->get()->all();
        return view('admin.anggota.beranda', compact('data', 'no'));
    }
    public function dataAjax(Request $request)
    {
        $data = [];
        if ($request->has('q')) {
            $search = $request->q;
            $data = DB::table("pekerjaans")
                ->select("id", "pekerjaan")
                ->where('pekerjaan', 'LIKE', "%$search%")
                ->get();
        }


        return response()->json($data);
    }
    public function create()
    {
        $pekerjaan = Pekerjaan::orderBy('id', 'ASC')->get()->all();
        return view('admin.anggota.create', compact('pekerjaan'));
    }

    public function store(Request $request)
    {
        $data = $request->all();
        Anggota::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Anggota " . $request->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $request->nama . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.anggota.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $pekerjaan = Pekerjaan::orderBy('id', 'ASC')->get()->all();
        $data = Anggota::findOrFail($id);
        return view('admin.anggota.edit', compact('data', 'pekerjaan'));
    }

    public function update(Request $request, $id)
    {
        $data = Anggota::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Anggota " . $request->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $request->nama . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.anggota.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Anggota::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Anggota " . $data->nama;
        History::create($histori);

        $notification = array(
            'message' => 'Data Anggota "' . $data->nama . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.anggota.index')->with($notification);
    }
}

resources/views/admin/anggota/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Anggota
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2">
                <a href="{{ route('admin.anggota.create') }}" class="btn btn-primary">+ Anggota</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-success" href="{{ route('export') }}">Download Data Anggota</a><br><br>
            </div>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Anggota</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Anggota ID</th>
                                <th>No Kapling</th>
                                <th>Nama</th>
                                <th>Leader</th>
                                <th>Sistem Bayar</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->id }}</td>
                                <td>{{ $item->no_kapling }}</td>
                                <td>{{ $item->nama }}</td>
                                <td>{{ $item->leader }}</td>
                                <td>{{ $item->sistem_bayar }}</td>
                                <td align="center">
                                    <form action="{{ route('admin.anggota.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal-barang{{$item->id }}">Lihat</a>
                                        <a class="btn btn-success" href="{{ route('admin.anggota.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            <!-- Anggota -->
                            <div class="modal fade in" id="modal-barang{{$item->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span></button>
                                            <h4 class="modal-title">
                                                Data {{$item->nama}}
                                            </h4>
                                        </div>

                                        <div class="box-body">
                                            <div class="col-md-4">
                                                NIK
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->no_ktp }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Tempat Tanggal Lahir
                                            </div>
                                            <div class="col-md-8">
                                                @if(empty($item->tanggal_lahir))
                                                : {{ $item->tempat_lahir }},
                                                @else
                                                : {{ $item->tempat_lahir }}, {{ tanggal_local($item->tanggal_lahir) }}
                                                @endif
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Jenis Kelamin
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->jk }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Alamat
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->alamat }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                No Telp
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->no_telp }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Pekerjaan
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->pekerjaan->pekerjaan }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Tanam Pohon
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->tanam_pohon }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Kepemilikan Jadi SHM
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->jadi_shm }}
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                Keterangan
                                            </div>
                                            <div class="col-md-8">
                                                : {{ $item->ket }}
                                            </div>
                                        </div>
                                        <div class="box-footer">
                                            <button class="btn btn-default pull-left" data-dismiss="modal">Tutup</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/anggota/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Anggota
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data Anggota</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.anggota.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <input type="text" name="nama" class="form-control" placeholder="Nama">
                                    <small class="text-danger">{{ $errors->first('nama') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">NIK</label>

                                <div class="col-sm-8">
                                    <input type="number" name="no_ktp" class="form-control" placeholder="NIK">
                                    <small class="text-danger">{{ $errors->first('no_ktp') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tempat Lahir</label>

                                <div class="col-sm-8">
                                    <input type="text" name="tempat_lahir" class="form-control" placeholder="Tempat Lahir">
                                    <small class="text-danger">{{ $errors->first('tempat_lahir') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanggal Lahir</label>

                                <div class="col-sm-8">
                                    <input type="date" name="tanggal_lahir" class="form-control">
                                    <small class="text-danger">{{ $errors->first('tanggal_lahir') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jenis Kelamin</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="jk">
                                        <option value="Perempuan">Perempuan</option>
                                        <option value="Laki - Laki">Laki - Laki</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('jk') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Alamat</label>

                                <div class="col-sm-8">
                                    <input type="text" name="alamat" class="form-control" placeholder="Alamat">
                                    <small class="text-danger">{{ $errors->first('alamat') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">No Telp</label>

                                <div class="col-sm-8">
                                    <input type="text" name="no_telp" class="form-control" placeholder="No Telp">
                                    <small class="text-danger">{{ $errors->first('no_telp') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pekerjaan</label>

                                <div class="col-sm-8">
                                    <select class="select2 form-control" name="pekerjaan_id">
                                        @foreach($pekerjaan as $pek)
                                        <option value="{{$pek->id}}">{{$pek->pekerjaan}}</option>
                                        @endforeach
                                    </select>
                                    <small class="text-danger">{{ $errors->first('pekerjaan_id') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Blok Kaveling</label>

                                <div class="col-sm-8">
                                    <input type="text" name="no_kapling" class="form-control" placeholder="No Kapling">
                                    <small class="text-danger">{{ $errors->first('no_kapling') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Sistem Bayar</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="sistem_bayar">
                                        <option value="Cash">Cash</option>
                                        <option value="DP">DP</option>
                                        <option value="Kredit">Kredit</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('sistem_bayar') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Dana</label>

                                <div class="col-sm-8">
                                    <input type="number" name="dana" class="form-control" placeholder="Dana">
                                    <small class="text-danger">{{ $errors->first('dana') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Leader</label>

                                <div class="col-sm-8">
                                    <input type="text" name="leader" class="form-control" placeholder="Leader">
                                    <small class="text-danger">{{ $errors->first('leader') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanam Pohon</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="tanam_pohon">
                                        <option value="Tidak Setuju">Tidak Setuju</option>
                                        <option value="Setuju">Setuju</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('tanam_pohon') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jadi SHM</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="jadi_shm">
                                        <option value="Tidak Setuju">Tidak Setuju</option>
                                        <option value="Setuju">Setuju</option>
                                    </select>
                                    <small class="text-danger">{{ $errors->first('jadi_shm') }}</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label">Keterangan</label>

                                <div class="col-sm-8">
                                    <input type="text" name="ket" class="form-control" placeholder="Keterangan">
                                    <small class="text-danger">{{ $errors->first('ket') }}</small>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/anggota')}}" class="btn btn-default  pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.select2').select2({
        ajax: {
            url: '{{url('admin-anggota-ajax')}}',
            dataType: 'json',
            delay: 250,
            processResults: function(data) {
                return {
                    results: $.map(data, function(item) {
                        return {
                            text: item.pekerjaan,
                            id: item.id
                        }
                    })
                };
            },
            cache: true
        }
    });
</script>
@endsection