routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/home', function () {
    return redirect('/admin/beranda');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin-anggota-ajax', 'Web\Admin\AnggotaController@dataAjax');
Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::get('admin/angsuran/index/{id}', 'Web\Admin\AngsuranController@index', ['as' => 'admin']);

Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('export', 'Web\Admin\DownloadController@export_anggota')->name('export');
//cteak formulir
Route::get('admin/akad/cetak/formulir', 'Web\Admin\AkadController@formulir')->name('admin.akad.cetak.formulir');

app/Angsuran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Angsuran extends Model
{
    protected $guarded = [];

    protected $dates = ['tanggal'];
    public function akad()
    {
        return $this->belongsTo('App\Akad', 'akad_id');
    }
}

app/Http/Controllers/Web/Admin/AngsuranController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Angsuran;
use App\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AngsuranController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request, $id)
    {
        $no = 1;
        $akad_id = $id;
        $data = Angsuran::where('akad_id', $id)->get()->all();
        return view('admin.angsuran.beranda', compact('data', 'no', 'akad_id'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $data['akad_id'] = $request->akad_id;
        $data['tanggal'] = $request->tanggal;
        $data['jml'] = $request->jml;

        Angsuran::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Tanggal Pembayaran Akad.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Tanggal Pembayaran Akad berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->back()->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Angsuran::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Tanggal Pembayaran Akad.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Tanggal Pembayaran Akad berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->back()->with($notification);
    }
}

resources/views/admin/angsuran/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Jadwal Pembayaran Angsuran
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Jadwal Pembayaran Angsuran</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.angsuran.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanggal Pembayaran</label>

                                <div class="col-sm-8">
                                    <input type="date" name="tanggal" class="form-control">
                                    <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Jumlah</label>

                                <div class="col-sm-8">
                                    <input type="number" name="jml" class="form-control" placeholder="Jumlah">
                                    <small class="text-danger">{{ $errors->first('barang') }}</small>
                                </div>
                            </div>
                            <input type="hidden" name="akad_id" value="{{$akad_id}}">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Tanggal</th>
                                <th>Jumlah</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ tanggal_local($item->tanggal) }}</td>
                                <td>Rp. {{ number_format($item->jml, 0, ".", ".")}},-</td>
                                <td align="center">
                                    <form action="{{ route('admin.angsuran.destroy',$item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <a href="{{url('admin/akad')}}" class="btn btn-default">Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection