routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/home', function () {
    return redirect('/admin/beranda');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController', ['as' => 'admin']);
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin-anggota-ajax', 'Web\Admin\AnggotaController@dataAjax');
Route::resource('admin/akad', 'Web\Admin\AkadController', ['as' => 'admin']);
Route::get('admin-akad-ajax', 'Web\Admin\AkadController@dataAjax');
Route::resource('admin/angsuran', 'Web\Admin\AngsuranController', ['as' => 'admin']);
Route::get('admin/angsuran/index/{id}', 'Web\Admin\AngsuranController@index', ['as' => 'admin']);

Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);

Route::get('admin/upload/anggota', 'Web\Admin\UploadController@anggota')->name('admin.upload.anggota');
Route::post('admin/import/anggota', 'Web\Admin\UploadController@import_anggota')->name('admin.import.anggota');

Route::get('admin/upload/akad', 'Web\Admin\UploadController@akad')->name('admin.upload.akad');
Route::post('admin/import/akad', 'Web\Admin\UploadController@import_akad')->name('admin.import.akad');

Route::get('admin/upload/jpa', 'Web\Admin\UploadController@jpa')->name('admin.upload.jpa');
Route::post('admin/import/jpa', 'Web\Admin\UploadController@import_jpa')->name('admin.import.jpa');

Route::get('export', 'Web\Admin\DownloadController@export_anggota')->name('export');
//cteak formulir
Route::get('admin/akad/cetak/formulir', 'Web\Admin\AkadController@formulir')->name('admin.akad.cetak.formulir');

app/Pekerjaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pekerjaan extends Model
{
    protected $guarded = [];

    public function anggota()
    {
        return $this->hasMany('App\Anggota');
    }
}

app/Http/Controllers/Web/Admin/PekerjaanController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\PekerjaanRequest;
use App\Pekerjaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PekerjaanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $data = Pekerjaan::where('pekerjaan', 'not like', '-')->orderBy('pekerjaan', 'ASC')->get()->all();
        return view('admin.pekerjaan.beranda', compact('data', 'no'));
    }

    public function create()
    {
        //
    }

    public function store(PekerjaanRequest $request)
    {
        $data = $request->all();
        Pekerjaan::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Pekerjaan " . $request->pekerjaan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pekerjaan "' . $request->pekerjaan . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.pekerjaan.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Pekerjaan::findOrFail($id);
        return view('admin.pekerjaan.edit', compact('data'));
    }

    public function update(PekerjaanRequest $request, $id)
    {
        $data = Pekerjaan::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Pekerjaan " . $request->pekerjaan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pekerjaan "' . $request->pekerjaan . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.pekerjaan.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Pekerjaan::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Pekerjaan " . $data->pekerjaan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pekerjaan "' . $data->pekerjaan . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.pekerjaan.index')->with($notification);
    }
}

resources/views/admin/pekerjaan/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Pekerjaan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Pekerjaan</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.pekerjaan.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pekerjaan</label>

                                <div class="col-sm-8">
                                    <input type="text" name="pekerjaan" class="form-control" placeholder="Pekerjaan">
                                    <small class="text-danger">{{ $errors->first('pekerjaan') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>ID</th>
                                <th>Pekerjaan</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->id }}</td>
                                <td>{{ $item->pekerjaan }}</td>
                                <td align="center">
                                    <form action="{{ route('admin.pekerjaan.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.pekerjaan.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/pekerjaan/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Pekerjaan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Pekerjaan</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.pekerjaan.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Pekerjaan</label>

                                <div class="col-sm-8">
                                    <input type="text" value="{{$data->pekerjaan}}" name="pekerjaan" class="form-control" placeholder="Pekerjaan">
                                    <small class="text-danger">{{ $errors->first('pekerjaan') }}</small>
                                </div>
                            </div>

                            <a href="{{url('admin/pekerjaan')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection